eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
server:
  port: 8500
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: orderServer
          uri: lb://orderServer
          predicates:
            - Path=/api/orderServer/**
          filters:
            - StripPrefix=2
        - id: goodsServer
          uri: lb://goodsServer
          predicates:
            - Path=/api/goodsServer/**
          filters:
            - StripPrefix=2


